server {
    listen 80;
    
    # Это перенаправление для API
    location /api/ {
        proxy_set_header Host $host;
        proxy_pass http://backend:8000/api/;
    }

    # Это перенаправление для Админки
    location /admin/ {
        proxy_set_header Host $host;
        proxy_pass http://backend:8000/admin/;
    }

    # Это для статики (картинки, CSS)
    location /static/ {
        alias /backend_static/static/;
    }

    # Это для фронтенда
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}